# Generated by Django 2.0.1 on 2018-07-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_time', models.DateTimeField(auto_now_add=True)),
                ('mess_to', models.CharField(max_length=50)),
                ('mess_from', models.CharField(max_length=50)),
                ('mess_content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=50)),
                ('svid', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('vulnerability', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
                ('match_mode', models.CharField(max_length=50)),
                ('match', models.CharField(max_length=200)),
                ('vul_function', models.CharField(default=None, max_length=30)),
                ('main_function', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rusults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rusults_tasks_id', models.IntegerField()),
                ('results_owner', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=100)),
                ('analysis', models.CharField(max_length=50)),
                ('code_content', models.TextField()),
                ('commit_author', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=100)),
                ('svid', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=10)),
                ('line_number', models.IntegerField()),
                ('rule_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tampers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tam_name', models.CharField(max_length=30)),
                ('tam_types', models.IntegerField()),
                ('tam_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_user', models.CharField(max_length=50)),
                ('task_name', models.CharField(max_length=50)),
                ('task_stime', models.DateTimeField(auto_now_add=True)),
                ('task_status', models.CharField(max_length=30)),
                ('task_details', models.TextField()),
                ('task_filename', models.CharField(max_length=50)),
                ('rule_list', models.CharField(max_length=100)),
                ('tamper_list', models.CharField(max_length=100)),
            ],
        ),
    ]
