[supervisord]
nodaemon=false
logfile=/home/ubuntu/.hermes/hermes-agent/Kunlun-M/supervisor/supervisord.log
pidfile=/home/ubuntu/.hermes/hermes-agent/Kunlun-M/supervisor/supervisord.pid

[program:kunlun-web]
command=/home/ubuntu/Kunlun-M-venv/bin/gunicorn --preload -w 1 -b 127.0.0.1:9999 Kunlun_M.wsgi:application
directory=/home/ubuntu/.hermes/hermes-agent/Kunlun-M
autostart=true
autorestart=true
startsecs=20
stdout_logfile=/home/ubuntu/.hermes/hermes-agent/Kunlun-M/supervisor/kunlun-web-stdout.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile=/home/ubuntu/.hermes/hermes-agent/Kunlun-M/supervisor/kunlun-web-stderr.log
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=3

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[inet_http_server]
port=127.0.0.1:9001

[supervisorctl]
serverurl=http://127.0.0.1:9001
