# Generated by Django 2.0.1 on 2018-07-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svid', models.CharField(max_length=22)),
                ('taskid', models.IntegerField()),
                ('status', models.IntegerField()),
                ('msg', models.CharField(max_length=50)),
            ],
        ),
    ]
