# Generated by Django 3.0.7 on 2021-06-23 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewEvilFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svid', models.IntegerField()),
                ('scan_task_id', models.IntegerField()),
                ('func_name', models.CharField(max_length=200)),
                ('origin_func_name', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=50)),
                ('svid', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('status', models.BooleanField(default=True)),
                ('match_mode', models.CharField(max_length=50)),
                ('match', models.CharField(max_length=500)),
                ('match_name', models.CharField(default=None, max_length=100, null=True)),
                ('black_list', models.CharField(default=None, max_length=100, null=True)),
                ('keyword', models.CharField(default=None, max_length=200, null=True)),
                ('unmatch', models.CharField(default=None, max_length=200, null=True)),
                ('vul_function', models.CharField(default=None, max_length=30, null=True)),
                ('main_function', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ScanResultTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_task_id', models.IntegerField()),
                ('result_id', models.IntegerField()),
                ('cvi_id', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('vulfile_path', models.CharField(max_length=200)),
                ('source_code', models.CharField(max_length=200)),
                ('result_type', models.CharField(max_length=100)),
                ('is_unconfirm', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('target_path', models.CharField(max_length=300)),
                ('parameter_config', models.CharField(max_length=100)),
                ('last_scan_time', models.DateTimeField(auto_now=True)),
                ('visit_token', models.CharField(default=uuid.uuid4, max_length=64)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tampers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tam_name', models.CharField(max_length=30)),
                ('tam_type', models.CharField(max_length=100)),
                ('tam_key', models.CharField(max_length=200)),
                ('tam_value', models.CharField(max_length=200)),
            ],
        ),
    ]
