# Generated by Django 3.0.7 on 2021-07-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='vul_function',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='parameter_config',
            field=models.CharField(max_length=500),
        ),
    ]
