# Generated by Django 3.0.7 on 2020-08-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_remove_rules_vulnerability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='vul_function',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
