# Generated by Django 3.0.7 on 2021-07-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210701_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='level',
            field=models.IntegerField(default=5, max_length=2),
        ),
    ]
