# Generated by Django 3.0.7 on 2020-08-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200813_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='black_list',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='keyword',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='match_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rules',
            name='unmatch',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rules',
            name='match',
            field=models.CharField(max_length=500),
        ),
    ]
