# Generated by Django 3.0.7 on 2021-07-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_rules_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_des', models.TextField(null=True)),
                ('project_origin', models.CharField(max_length=500, null=True)),
                ('project_hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='scanresulttask',
            name='result_id',
        ),
        migrations.AddField(
            model_name='newevilfunc',
            name='func_hash',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='newevilfunc',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='scan_project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='vul_hash',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='scantask',
            name='project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='task_name',
            field=models.CharField(max_length=200),
        ),
    ]
