# Generated by Django 3.0.7 on 2020-08-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200813_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tampers',
            name='tam_type',
            field=models.CharField(max_length=100),
        ),
    ]
