# Generated by Django 3.0.7 on 2021-07-21 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210720_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50, null=True)),
                ('language', models.CharField(max_length=20)),
                ('ext', models.CharField(default=None, max_length=100, null=True)),
                ('hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='scantask',
            name='last_scan_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
