# Generated by Django 3.0.7 on 2021-07-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210721_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='level',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='parameter_config',
            field=models.TextField(),
        ),
    ]
