# Generated by Django 3.0.7 on 2020-08-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200814_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresulttask',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
