# Generated by Django 3.0.7 on 2021-08-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20210723_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorVulns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vuln_id', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('severity', models.IntegerField()),
                ('cves', models.TextField()),
                ('reference', models.TextField()),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_version', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
