# Generated by Django 3.0.7 on 2021-08-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_vendorvulns'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='vendorvulns',
        #     name='vendor_version',
        # ),
        # migrations.AddField(
        #     model_name='vendorvulns',
        #     name='affected_versions',
        #     field=models.TextField(null=True),
        # ),
        migrations.RenameField(
            model_name='vendorvulns',
            old_name='vendor_version',
            new_name='affected_versions',
        ),
        migrations.AlterField(
            model_name='vendorvulns',
            name='affected_versions',
            field=models.TextField(null=True),
        )
    ]
