# Generated by Django 3.0.7 on 2020-08-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_scanresulttask_rule_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanresulttask',
            name='rule_type',
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='rusult_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
