# Generated by Django 3.0.7 on 2021-12-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20210816_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectvendors',
            name='source',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
