# Generated by Django 3.0.7 on 2020-08-18 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20200818_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresulttask',
            name='is_unconfirm',
            field=models.BooleanField(default=False),
        ),
    ]
