# Generated by Django 3.0.7 on 2020-08-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_scanresulttask_is_unconfirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewEvilFunc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svid', models.IntegerField()),
                ('func_name', models.CharField(max_length=200)),
                ('origin_func_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
