# Generated by Django 3.0.7 on 2020-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_auto_20200820_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='newevilfunc',
            name='scan_task_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
