# Generated by Django 3.0.7 on 2021-06-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_newevilfunc_scan_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='visit_token',
            field=models.CharField(default='S43I0TFIRJSBXO6MIBN61716JI077LFV3CYPIXR1TRELXYVZSDK1XQP7Q3HURMB6', max_length=64),
        ),
    ]
