# Generated by Django 5.2.14 on 2026-06-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_frameworktamper_delete_tampers'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaintChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_task', models.IntegerField(db_index=True)),
                ('vul_result', models.IntegerField(db_index=True)),
                ('chain_index', models.IntegerField(default=0)),
                ('step_order', models.IntegerField(default=0)),
                ('node_label', models.CharField(max_length=50)),
                ('node_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=500)),
                ('lineno', models.IntegerField(default=0)),
                ('vid', models.IntegerField(blank=True, null=True)),
                ('source_code', models.TextField(default='')),
            ],
            options={
                'db_table': 'taint_chain',
                'ordering': ['vul_result', 'chain_index', 'step_order'],
                'indexes': [models.Index(fields=['scan_task', 'vul_result'], name='taint_chain_scan_ta_f5dd65_idx'), models.Index(fields=['vul_result', 'chain_index'], name='taint_chain_vul_res_afc378_idx')],
            },
        ),
    ]
