# Generated by Django 3.0.7 on 2021-06-16 09:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_scantask_visit_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scantask',
            name='visit_token',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
    ]
