# Generated by Django 5.2.14 on 2026-09-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_add_verification_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresulttask',
            name='verification_status',
            field=models.CharField(choices=[('', '未确认'), ('tp', 'True Positive'), ('fp', 'False Positive'), ('pending', '待验证'), ('unknown', '无法判断')], db_index=True, default='', max_length=10),
        ),
    ]
