# Generated by Django 5.2.14 on 2026-09-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_alter_scanresulttask_verification_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('base_url', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI配置',
            },
        ),
    ]
