# Generated by Django 5.2.14 on 2026-09-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_aiconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAiReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('report_json', models.TextField(default='')),
                ('vuls_fingerprint', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='ai_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='ai_confidence',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='ai_fix',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='ai_reasoning',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='ai_severity_adjust',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='scanresulttask',
            name='ai_verdict',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
