# Generated by Django 5.2.14 on 2026-09-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_projectaireport_scanresulttask_ai_analyzed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiTriageQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('processed', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
