# Generated by Django 5.2.14 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_aitriagequeue'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('lessons', '判定经验教训'), ('engine', '引擎缺陷清单'), ('log', '裁决台账')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content_md', models.TextField()),
                ('data_baseline', models.CharField(default='', help_text='生成时的数据规模描述', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DiscussionDoc',
                'verbose_name_plural': 'DiscussionDoc',
                'db_table': 'discussion_doc',
                'ordering': ('-created_at',),
            },
        ),
    ]
