# Generated by Django 5.2.14 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_discussiondoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerdictEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul_id', models.IntegerField(db_index=True)),
                ('old_status', models.CharField(default='', max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('human', '人工标记'), ('ai-adjudication', 'AI 改判采信'), ('precedent-adoption', '判例采纳'), ('undo', '撤销'), ('genesis', '建账回填'), ('bulk', '批量操作')], max_length=30)),
                ('actor', models.CharField(default='', max_length=80)),
                ('notes', models.TextField(blank=True, default='')),
                ('cvi_id', models.CharField(default='', max_length=20)),
                ('scan_project_id', models.IntegerField(default=0)),
                ('pattern_hash', models.CharField(default='', help_text='判定时的源码模式指纹', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'VerdictEvent',
                'verbose_name_plural': 'VerdictEvent',
                'db_table': 'verdict_event',
                'ordering': ('-created_at',),
            },
        ),
    ]
